# Generated by Django 4.2 on 2023-04-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_is_staff1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff1',
        ),
    ]
